<a href="https://colab.research.google.com/github/Kaif974/Assignment_1/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Q1.Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [1]:
import numpy as np

arr = np.random.randint(1, 101, size=(3, 3))
transposed_arr = arr.T
print("Original Array:\n", arr)
print("Transposed Array:\n", transposed_arr)


Original Array:
 [[82 81 14]
 [90 38  3]
 [19 38 99]]
Transposed Array:
 [[82 90 19]
 [81 38 38]
 [14  3 99]]


Q2.Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

In [2]:
arr = np.arange(10)
arr_2x5 = arr.reshape(2, 5)
arr_5x2 = arr.reshape(5, 2)
print("1D Array:\n", arr)
print("2x5 Array:\n", arr_2x5)
print("5x2 Array:\n", arr_5x2)


1D Array:
 [0 1 2 3 4 5 6 7 8 9]
2x5 Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]
5x2 Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Q3.Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [3]:
arr = np.random.rand(4, 4)
bordered_arr = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("Original 4x4:\n", arr)
print("6x6 with border:\n", bordered_arr)


Original 4x4:
 [[0.03059608 0.4557446  0.05010444 0.07696253]
 [0.15048332 0.56733385 0.74700103 0.66237709]
 [0.01089015 0.99704611 0.85775441 0.37653992]
 [0.99828322 0.09300096 0.20881329 0.61863617]]
6x6 with border:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.03059608 0.4557446  0.05010444 0.07696253 0.        ]
 [0.         0.15048332 0.56733385 0.74700103 0.66237709 0.        ]
 [0.         0.01089015 0.99704611 0.85775441 0.37653992 0.        ]
 [0.         0.99828322 0.09300096 0.20881329 0.61863617 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


Q4.Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [4]:
arr = np.arange(10, 61, 5)
print("Array:", arr)


Array: [10 15 20 25 30 35 40 45 50 55 60]


Q5.Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations.

In [5]:
arr = np.array(['python', 'numpy', 'pandas'])
print("Uppercase:", np.char.upper(arr))
print("Lowercase:", np.char.lower(arr))
print("Title Case:", np.char.title(arr))


Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']


Q6.Generate a NumPy array of words. Insert a space between each character of every word.

In [6]:
arr = np.array(['hello', 'world'])
spaced = np.char.join(' ', arr)
print("Spaced Words:", spaced)


Spaced Words: ['h e l l o' 'w o r l d']


Q7.Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [7]:
a = np.random.randint(1, 10, size=(2, 2))
b = np.random.randint(1, 10, size=(2, 2))

print("Addition:\n", a + b)
print("Subtraction:\n", a - b)
print("Multiplication:\n", a * b)
print("Division:\n", a / b)


Addition:
 [[11 15]
 [10 14]]
Subtraction:
 [[5 3]
 [4 0]]
Multiplication:
 [[24 54]
 [21 49]]
Division:
 [[2.66666667 1.5       ]
 [2.33333333 1.        ]]


Q8.Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [8]:
identity = np.eye(5)
diagonal = np.diag(identity)
print("Identity Matrix:\n", identity)
print("Diagonal Elements:", diagonal)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


Q9.Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [9]:
from sympy import isprime

arr = np.random.randint(0, 1000, size=100)
primes = arr[np.vectorize(isprime)(arr)]
print("Prime Numbers:", primes)


Prime Numbers: [967 409 241 431  11 263  79 449 613 647 881 877 283 859 701]


Q10.Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [11]:
temps = np.random.uniform(15, 35, size=28)
weekly_avg = temps.reshape(4, 7)
print("Weekly Averages:", weekly_avg.mean(axis=1))


Weekly Averages: [23.05113395 24.82961783 24.82679363 21.91704867]
